### ISSUE TITLE
error! Running Development mode

### ISSUE THREAD

**Issue by ava-world** [Argus-Labs/starter-game-template#53]
after creatig a new game name, i attempted to run development mode and saw this error

# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
Error: Encountered an error with Cardinal: exit status 1

i am currently using an ubuntu 20.04 virtualserver.
![2024-06-22 (1)](https://github.com/Argus-Labs/starter-game-template/assets/98952181/1deb2420-8247-4c5e-beb5-5db68b71e1cb)

**Comment by rmrt1n** [comment]
looks like you need to install some c libs. try running:
```bash
sudo apt update
sudo apt install build-essential
```

also try updating the world cli if this issue persists.

**Comment by smsunarto** [comment]
Hey @ava-world, to add on Ryan's solution, updating to the latest version of starter-game-template (or updating the cardinal version in go.mod) should also fix this issue. We've removed the cgo dependencies
